### ISSUE TITLE
Version 1.0.0 ToDo

### ISSUE THREAD

**Issue by henrikfroehling** [henrikfroehling/TraktApiSharp#16]
#### Version 1.0.0 Alpha 1
- [x] #17 New and better request implementation
- [x] #44 New and better response implementation
- [x] #34 Convert PCL to .NET Standard

#### Version 1.0.0 Alpha 2
- [x] #18 Reduce indirections in object properties
- [x] #20 Optimize deserialization of json data
- [x] #43 Remove Images option in TraktExtendedInfo
- [x] #59 System.NullReferenceException When getting popular shows

#### Version 1.0.0 Alpha 3
- [x] #21 Improve http client handling
- [x] #69 Add support for "networks" GET request (for version 1.0.0)
- [x] #70 Add support for "certifications/{type}" GET request (for version 1.0.0)
- [x] #71 Add support for "users/hidden/{section}" POST request (for version 1.0.0)
- [x] #72 Add support for "users/hidden/{section}/remove" POST request (for version 1.0.0)
- [x] #75 Optimize serialization of json data
- [x] #77 Fix serialization of objects in post builder
- [x] #78 Implement json deserialization for authorization objects
- [x] #79 Remove prefix Trakt from internal type names
- [x] #83 Add missing "network" property in ITraktSeason
- [x] #87 Move tests from old test project into new test project
- [x] #88 Add missing "last_episode" property in ITraktShowProgress
- [x] #89 Add "dolby_atmos" and "dts_x" in TraktMediaAudio
- [x] #103 Fix module tests
- [x] #106 Add support for X-Item-ID and X-Item-Type response headers
- [x] #107 Add support for "comments/{id}/item" GET request
- [x] #108 Add support for "comments/recent/{comment_type}/{type}" GET request
- [x] #109 Add support for "comments/{id}/likes" GET request
- [x] #110 Add missing "country" property in ITraktMovie
- [x] #111 Add "comment_count" property in ITraktMovie, ITraktShow, ITraktSeason and ITraktEpisode
- [x] #116 Add support for "people/{id}/lists/{type}/{sort}" GET request
- [x] #117 Add support for "comments/trending/{comment_type}/{type}?{include_replies}" GET request
- [x] #118 Add support for "comments/recent/{comment_type}/{type}?{include_replies}" GET request
- [x] #119 Add support for "comments/updates/{comment_type}/{type}?{include_replies}" GET request
- [x] #120 Add support for "lists/trending" GET request
- [x] #121 Add support for "lists/popular" GET request
- [x] #122 Add support for "include_replies" parameter in "users/id/comments" GET request
- [x] #123 Make "sort_how" and "sort_by" optional in "users/{id}/lists" and "users/{id}/lists/{list_id}" requests
- [x] #124 Allow multiple types as filter in "users/{id}/lists/{list_id}/items/{type}" request
- [x] #129 Add "reset_at" property in ITraktShowWatchedProgress
- [x] #130 Add flag for "progress_watched_reset" section in TraktHiddenItemsSection

#### Version 1.0.0 Beta 1
- [x] #57 Move all examples into their own repository
- [x] #58 Rename library / project / repository to "Trakt.NET"
- [x] #105 Add tests for object json serialization
- [x] #134 Improve test coverage

**Comment by tidusjar** [comment]
Any plans to support .Net Standard?

**Comment by henrikfroehling** [comment]
Version 1.0.0-alpha1 (the one from yesterday) already supports. NET Standard 1.2. See issue #34 for more info.

**Comment by henrikfroehling** [comment]
https://github.com/henrikfroehling/Trakt.NET/issues/4
